#!/bin/bash
#
# /etc/init.d/cloudmanager
#
# This is the init script for starting up the
#  CloudManagerHA
#
# chkconfig: 345 89 11
# description: Starts and stops the CloudManagerHA daemon.
#

home=/root/cloudmanager_ha
startup=$home/cloudmanager_ha_server.py
#shutdown=$home/bin/shutdown.sh

start() {
  echo $"Starting CloudManagerHA service:..."
  python $startup & >/dev/null 2>&1
  if [ "$?" == "0" ];then
     sleep 3
     echo  "Start successfully."
  else
     echo  "Start failed,see the log file for detail."
  fi
}

stop() {
  echo $"Stopping CloudManagerHA service:..."
  pid=`ps -aef | grep cloudmanager_ha_server | grep -v grep | awk '{print $2}'`
  for i in $pid
  do
      kill $i >/dev/null 2>&1
      sleep 3s
  done
  ps -aef | grep cloudmanager_ha_server | grep -v grep >/dev/null 2>&1
  if [ "$?" == "0" ];then
     for i in $pid
     do
        kill -9 $i >/dev/null 2>&1
     done
  fi
  lsof -i:7788 >/dev/null 2>&1
  if [ "$?" == "0" ];then
	  service mysqld restart >/dev/null 2>&1
	  service keepalived restart > /dev/null 2>&1
	  service cloudmanager restart > /dev/null 2>&1 
  fi

  echo  "Stop successfully."
}

restart() {
  stop
  start
}

status() {
  ps -aef | grep cloudmanager_ha_server | grep -v grep >/dev/null 2>&1
  if [ "$?" == "0" ];then
      echo "cloudmanagerHA is running."
  else
      echo "cloudmanagerHA is stopped."
  fi
}

reset(){
	#stop cloudmanagerHA server
	stop
	#reset cloudmanager_ha conf
	$home/cloudmanager_ha_conf.sh recover
	#reset mysql cloudmanager_ha 
    /etc/init.d/mysqld restart >/dev/null 2>&1
    /etc/init.d/cloudmanager restart > /dev/null 2 >&1
}

# Handle the different input options
case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
status)
  status
  ;;
restart)
  restart
  ;;
reset)
  reset
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status|reset}"
  exit 1
esac

